#!/bin/bash

TEST="EventLoop"
INCLUDES=" ../EventHandling/EventQueue.cs ../HighResolutionDateTime.cs stubsRepWordGenerator.cs"

mcs Test"$TEST".cs ../EventHandling/"$TEST".cs $INCLUDES -d:TESTING &&
mono Test"$TEST".exe
