#!/bin/bash

TEST="Uniformity"
INCLUDES="stubsRepWordGenerator.cs ../Experiments/RepWordGenerator.cs ../Experiments/ExperimentState.cs"

mcs Test"$TEST".cs $INCLUDES -d:TESTING &&
mono Test"$TEST".exe
